name: 👔 Job Board - Archive all jobs
on:
  workflow_dispatch
jobs:
  archive-jobs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Archive jobs
      uses: crocoder-dev/crocoder-jobboard-action@master
      with:
        author-name: ${{ secrets.BOT_NAME }}
        author-email: ${{ secrets.BOT_EMAIL }}
        github-token: ${{ secrets.GIT_TOKEN }}
        jobboard-api: ${{ secrets.JOBBOARD_API_URL }}
        jobboard-token: ${{ secrets.JOBBOARD_AUTH_TOKEN }}
        starting-branch: development
        command: 'ARCHIVE_ALL'
        asignees: 'davidabram'
