name: 🐊 Company Staging - Deploy Website
on:
  workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Node setup
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry: https://npm.pkg.github.com/
        scope: "@crocoder"
    - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GIT_TOKEN }}" > ~/.npmrc
    - run: ./scripts/company/get-secrets.sh ${{ secrets.SECRET_BUCKET }} ./
    - run: cp scripts/robots/robots.txt packages/company/website/static
    - run: cd packages/company/website && yarn install --production=false
    - run: cd packages/company/website && yarn build
    - run: cd packages/company/website && npx serverless deploy --env=staging --conceal
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
    - run: DISTRIBUTION=${{ secrets.COMPANY_STAGING_WEBSITE_DISTRIBUTION }} ./scripts/invalidate/invalidate.sh



