name: 👔 Job Board - Deploy Website
on:
  workflow_dispatch:
  schedule:
  - cron: "0 8 * * 1-5"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Node setup
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry: https://npm.pkg.github.com/
        scope: "@crocoder"
    - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GIT_TOKEN }}" > ~/.npmrc
    - run: ./scripts/jobboard/get-secrets.sh ${{ secrets.SECRET_BUCKET }} ./
    - run: cd packages/jobboard/website && yarn install --production=false
    - run: cd packages/jobboard/website && yarn build:social
    - run: cd packages/jobboard/website && yarn social
    - run: cd packages/jobboard/website && yarn build
    - run: cd packages/jobboard/website && npx serverless deploy --conceal     
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
    - run: DISTRIBUTION=${{ secrets.JOBBOARD_WEBSITE_DISTRIBUTION }} ./scripts/invalidate/invalidate.sh



